<a href="https://colab.research.google.com/github/GUSTAVOPERALTA1/spark_colab/blob/main/NumPy%26Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

In [1]:
import numpy as np

In [2]:
#Definir lista de Python
lista =  [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
#Llevar una lista de Python a un objeto array de NumPy
arr = np.array(lista)

In [4]:
#Ver tipo de objeto
type(arr)

numpy.ndarray

## Crear objeto de multiples dimensiones (Matriz)

In [5]:
#Asignar valores a la matriz
matriz = [[1,2,3],[4,5,6],[7,8,9]]

#Pasarlo a NumPy
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Indexing

Ingresar al contenido de la lista a traves de su index

In [6]:
#PRUEBA INDEXING CON ARRAY

arr[0]+ arr[5] #Operaciones con los valores mediante su index

7

In [7]:
#PRUEBA INDEXING CON MATRIZ
matriz


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
#El nivel 0 ingresa a la primera posición a nivel de filas ([1,2,3])
matriz[0]

array([1, 2, 3])

In [9]:
#Ingresar a la lista y extraer un valor de la misma
#Primero definir fila y luego columnas
matriz[0,2]

3

### Slicing

Se utiliza para especificar cómo dividir una secuencia. Funciona con un start y un end
En ciencia de datos ayuda a la navegación en el array

In [10]:
  arr[0:3]

array([1, 2, 3])

In [11]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [12]:
#Ir de la posición seleccionada al final
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [13]:
#Tomar todo el array e iterar entre ellos. (Iterar de 3 en 3)
arr[::3]

array([1, 4, 7])

In [14]:
#Toma el primer valor del final al comienzo
arr[-1]

9

In [15]:
#Slicing en Matriz

#De 1 hacia adelante.
matriz[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [16]:
#De uno hacia adelante, a nivel de columnas de 0 a 2
matriz[1:, 0:2]

array([[4, 5],
       [7, 8]])

## Tipos de datos

In [17]:
#.dtype ayuda a conocer el tipo de dato del array
array = np.array([0,1,2,3,4])

In [18]:
#Convertir el tipo de dato de un array ya creado
#np.float64 : flotante
#np.int64 : entero
#np.bool_ : booleano
#np.string_ : cadena
#np.int8 : entero
array = array.astype(np.string_)
array.dtype
array

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [19]:
#Asignar el propio DTYPE
array = np.array([1,2,3,4], dtype = 'float64')
array.dtype

dtype('float64')

##Dimensiones

**Scalar**

Un único valor que no está dentro de una estructura

**Vector**

Cuando se tiene una lista de cualquier tipo de dato y con una sola dimensión.

**Matriz**

Una lista de dos dimensiones (filas y columnas).

**Tensor**

Sin un número exacto de dimensiones.


In [20]:
#Definición de un scalar
scalar = np.array(43)

#Conocer el número de dimensiones
scalar.ndim

0

In [21]:
#Definición de vector
vector = np.array([1,2,3])
vector.ndim

1

In [22]:
#Definición de un tensor (matriz dentro de otra matriz)
tensor = np.array([[[4,5,6],[7,8,9]], [[12,34,445],[45,2,456]]])
print(tensor)
tensor.ndim

[[[  4   5   6]
  [  7   8   9]]

 [[ 12  34 445]
  [ 45   2 456]]]


3

### Agregar o eliminar dimensiones

In [23]:
#Definir el número de dimensiones creadas con NDMIN
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [24]:
#Expandir una unica dimensión en el eje de un array, usando AXIS
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [25]:
#Eliminar dimensiones, SQUEEZE va a llevar al número de dimensiones que se cree correcta.
print(vector, vector.ndim)
vector2 = np.squeeze(vector)
print(vector2, vector2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


## Creando arrays

In [26]:
#Codigo basado en Python para generar valores.
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
#ARANGE genera un arranche desde los valores definidos. (dato inicial, dato stock, step(iteración))
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [28]:
#ZEROS define un array compuesto solo por 0
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
#ONES define un array compuesto solo por 1
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [30]:
#LINSPACE tiene la siguiente estructura: (valor inicial, valor final, cuantos datos va a generar)
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [31]:
#EYE creará una matriz con la diagonal principal en 1 y lo demás en 0
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
#RANDOM.RAND genera numeros aleatorios entre 0 y 1
np.random.rand()
#Si se le da un parametro, generará un array con ese número de valores entre 0 y 1
np.random.rand(4,4)

array([[0.84181426, 0.14525687, 0.26113792, 0.30095489],
       [0.98132569, 0.88256963, 0.63980127, 0.93511653],
       [0.39506736, 0.92779605, 0.69311535, 0.84268133],
       [0.5761909 , 0.00950394, 0.56552369, 0.79588522]])

In [33]:
#Generar un entero aleatorio entre el rango que se defina
np.random.randint(1,15)

1

In [34]:
#Se generan números aleatorios entre 1 y 100, estos valores se almacenan en la tupla definida.
np.random.randint(1,100, (10,10))

array([[69, 76, 33, 97, 97, 39, 71, 63, 68, 93],
       [ 8, 39,  5, 30, 80, 66, 79, 71, 37, 75],
       [92, 21, 39, 24, 78, 91, 89, 17, 27, 98],
       [44, 29, 14, 51, 26, 60, 86, 76, 76, 87],
       [15,  1, 98, 44, 64,  8, 26, 77, 65, 86],
       [59, 32, 17, 50, 25, 85, 75, 60, 75, 83],
       [ 5, 18, 35, 80,  4, 95, 35, 58, 81, 42],
       [31, 35, 62, 62, 49, 81, 69, 70, 44, 76],
       [90, 48, 39, 37, 21, 50, 38, 82,  1, 29],
       [72, 74, 84, 31, 17, 80, 50,  4, 31, 31]])

## Shape y Reshape

Cuando se usa reshape se debe tomar en cuenta la estructura original de los elementos generados, es decir, mantener equivalente el número de valores con la forma que se brinda.

Ejemplo:
Un arreglo de (3,2) se puede reshapear a uno de (1,6), respetando que dentro existen 6 elementos.

In [35]:
#SHAPE indica la forma que tiene un arreglo. Da información de la estructura a trabajar.
arr = np.random.randint(1,10,(3,2))
arr.shape

(3, 2)

In [36]:
arr

array([[2, 1],
       [7, 3],
       [6, 3]])

In [37]:
#RESHAPE reestructura el array para adaptarlo a los parámetros dados.
#Útil para estandarizar estructuras.
arr.reshape(2,3)

array([[2, 1, 7],
       [3, 6, 3]])

In [38]:
#Otra forma de hacer reshape.
np.reshape(arr,(2,3))

array([[2, 1, 7],
       [3, 6, 3]])

In [39]:
#Hacer reshape especificando que se ejecute como lo haría en lenguaje C.
#RESHAPE tomando filas.
np.reshape(arr,(2,3),'C')

array([[2, 1, 7],
       [3, 6, 3]])

In [40]:
#Ordenar en lenguaje Fortran.
#Ordena por columnas.
np.reshape(arr,(2,3),'F')

array([[2, 6, 3],
       [7, 1, 3]])

In [41]:
#Ordenar de forma en como esta optimizado en el sistema donde corre.
#Define aleatoriamente si lo hace C o F.
np.reshape(arr,(2,3),'A')

array([[2, 1, 7],
       [3, 6, 3]])

## Funciones principales de NumPy

In [42]:
arr = np.random.randint(1,20,10)

In [43]:
matriz = arr.reshape(2,5)
matriz

array([[15,  5,  7,  4,  5],
       [ 8,  7,  9, 15, 15]])

### Funciones Estadísticas

In [44]:
#MAX traer el número más grande del array o matriz
arr.max()

15

In [45]:
matriz.max()

15

In [46]:
#Especificar por cuál eje buscar el valor
# Eje 1 es por fila
# Eje 0 por columna
matriz.max(0)

array([15,  7,  9, 15, 15])

In [47]:
#ARGMAX da el indice donde se encuentra el valor más grande del array
arr.argmax()

0

In [48]:
matriz.argmax(0)

array([0, 1, 1, 1, 1])

In [49]:
#MIN da el valor minimo en el array
arr.min()
matriz.min()

4

In [50]:
#ARGMIN da el indice donde se encuentra el valor más pequeño del array
matriz.argmin(1)
matriz.argmin()
matriz.argmin(0)

array([1, 0, 0, 0, 0])

In [51]:
#PTP (Pick to Pick) (Del pico más bajo al pico más alto)
#Da la diferencia entre uno y otro.
arr.ptp()

11

In [52]:
#Distancia ptp por ejes
matriz.ptp(0)
matriz.ptp(1)

array([11,  8])

In [53]:
#SORT ordena de menor a mayor los números. Útil para usar con PERCENTILE
arr.sort()

In [54]:
#PERCENTILE, cual es el valor que se encuentra en la mitad.
#Si es un número impar, hace la operación de los dos valores intermedios.
np.percentile(arr,50)

7.5

In [55]:
#MEDIAN, da la mediana de un arreglo o matriz.
#Para la matriz especificar el eje.
np.median(arr)
np.median(matriz,1)

array([ 5., 15.])

In [56]:
#STD da la desviación estandár.
np.std(arr)

4.171330722922842

In [57]:
#VAR, da la varianza.
np.var(arr)

17.4

In [58]:
#MEAN, da la media.
np.mean(arr)

9.0

###Concatenate

Unir array b con array a

In [59]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [60]:
#Ejercicio de alineación de arrays para poder concatenar.
b = np.expand_dims(b, axis=0)

In [61]:
np.concatenate((a,b), axis= 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
#Concatenar por eje 1 usando TRANSPUESTA, es decir cambiarle la forma a su viceversa
np.concatenate((a,b.T), axis= 1)

array([[1, 2, 5],
       [3, 4, 6]])

## Copy

.copy() permite copiar un array de NumPy en otra variable de tal forma que al modificar el nuevo array los cambios no se vean reflejados en el array original.

In [63]:
#Nuevo array
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
#Segmentar el array
trozo_de_arr = arr[0:6]

In [65]:
#Poner todos los valores en 0
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [66]:
#Hacer copia de un array con COPY
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [67]:
#Hacer todos los valores 100
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [68]:
#SIEMPRE HACER OPERACIONES EN COPY
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

## Condiciones

Las condiciones permiten hacer consultas más específicas.

In [69]:
arr = np.linspace(1,10,10, dtype= 'int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [70]:
#Condición aplicada directamente en el array, valores mayores a 5
#Genera una salida en booleanos.
indices_cond = arr > 5

In [71]:
#Hacer slicing usando la variable antes creada para mostrar solo los valores que cumplen esa condición
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [72]:
#Otra forma de hacer la condición anterior pero usando una doble condición.
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [73]:
#Cambiar los valores a partir de una condición.
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

## Operaciones

In [74]:
lista = [1,2]
lista

[1, 2]

In [75]:
#En python una entrada como la siguiente, duplicaría los valores almacenados en la lista en lugar de multiplicar uno por uno.
lista * 2

[1, 2, 1, 2]

In [76]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
arr2 = arr.copy()
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
#Al usar NumPy, se entiende que se espera una multiplicación por 2 a cada valor.
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [79]:
#Sumar 2
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [80]:
#Dividir
1 / arr

<ipython-input-80-054321d3491e>:2: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [81]:
#Elevar
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [82]:
#Toma posiciones indexadas y suma posición 1 de arr con posición 1 de arr2 y así sucesivamente
#Funciona con todas las operaciones aritméticas
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [83]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

In [84]:
#Operar con matrices.
#Hace las operaciones guiandose de los indices de cada matriz.
#Funciona con todas las operaciones aritméticas.
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [85]:
#MATMUL hacer operación matemática
matriz2.T
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [86]:
#@ para operar
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

# PANDAS

**Pandas maneja dos objetos principales:**

*Pandas Series*
1.   Operaciones Aritméticas
2.   Distintos tipos de datos
*Pandas DataFrame*
1. Parecido a las matrices
1. Es un objeto hecho de arrays en una matriz
2. Las filas (manual o indexada) y columnas (nombre) tienen índices
3. Distintos tipos de datos
4. Tamaño Variable

In [87]:
import pandas as pd

## Series y DataFrames

In [88]:
#Asignar valores e índices en una serie.
#Si no se le da índice, tomará uno por defecto.
psg_players = pd.Series(['Navas', 'Mbappe', 'Neymar', 'Messi'],
          index = [1, 7, 10, 30]
          )
psg_players

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [89]:
#Si se agrega de esta forma, se le dará un index predeterminado
psg_players = pd.Series(['Navas', 'Mpbappe', 'Neymar', 'Messi'])

In [90]:
#Pandas Series desde diccionario
dict = {1: 'Navas', 7: 'Mbappe', 10: 'Neymar', 30: 'Messi'}
pd.Series(dict)

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [91]:
psg_players[0:3]

0      Navas
1    Mpbappe
2     Neymar
dtype: object

In [92]:
#Definir estructura matricial a partir de un diccionario
dict = {'Jugador': ['Navas', 'Mpbappe', 'Neymar', 'Messi'],
 'Altura' : [183.0, 170.0, 170.0, 164.0],
 'Goles' : [2, 200, 200, 200]
 }

In [93]:
#CREAR DATAFRAME
df_players = pd.DataFrame(dict, index = [1, 7, 10, 30])

In [94]:
#Ver columnas
df_players.columns

Index(['Jugador', 'Altura', 'Goles'], dtype='object')

In [95]:
#Ver index
df_players.index

Int64Index([1, 7, 10, 30], dtype='int64')

## Leer archivos CSV y JSON

In [120]:
#Leer archivo CSV guardado en Drive.
#SEP para definir el separador de los datos.
#HEADER para determinar que fila es el encabezado.
#NAMES para definir los nombres de las columnas.
df_books = pd.read_csv('/content/drive/MyDrive/PandasNumPy/bestsellers-with-categories.csv',
            sep = ',',
            header = 0,
            names = ['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre']
            )

In [97]:
df_books.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

In [98]:
#Leer archivo JSON
pd.read_json('/content/drive/MyDrive/PandasNumPy/hpcharactersdataraw.json', typ = 'Series')

0       {'Name': 'Mrs. Abbott', 'Link': 'https://www.h...
1       {'Name': 'Hannah Abbott', 'Link': 'https://www...
2       {'Name': 'Abel Treetops', 'Link': 'https://www...
3       {'Name': 'Euan Abercrombie', 'Link': 'https://...
4       {'Name': 'Aberforth Dumbledore', 'Link': 'http...
                              ...                        
1935    {'Name': 'Georgi Zdravko', 'Link': 'https://ww...
1936    {'Name': 'Zograf', 'Link': 'https://www.hp-lex...
1937    {'Name': 'Zonko', 'Link': 'https://www.hp-lexi...
1938    {'Name': 'Valentina Vázquez', 'Link': 'https:/...
1939    {'Name': 'Zygmunt Budge', 'Link': 'https://www...
Length: 1940, dtype: object

## Filtrado con loc y iloc

In [99]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [100]:
#Slicing
df_books[0:4]

Name              Author  User Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7   
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   
3                   1984 (Signet Classics)       George Orwell          4.7   

   Reviews  Price  Year        Genre  
0    17350      8  2016  Non Fiction  
1     2052     22  2011      Fiction  
2    18979     15  2018  Non Fiction  
3    21424      6  2017      Fiction

In [101]:
#Filtrar por columnas
df_books[['Name', 'Author', 'Year']]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  Year  
0                    JJ Smith  2016  
1                Stephen King  2011  
2          Jordan B. Peterson  2018  
3               George Orwell  2017  
4    National Geographic Kids  2019  
..                        ...   ...  
545               Jeff Kinney  2019  
546               Jen Sincero  2016  
547               Jen Sincero  2017  
548               Jen Sincero  2018  
549               Jen Sincero  2019  

[550 rows x 3 columns]

### Loc

Filtra a nivel de filas y columnas.

In [102]:
#Selecciona desde el indice 0 al 4.
#Muestra las columnas Name y Author
df_books.loc[0:4, ['Name','Author']]

Name                    Author
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

In [103]:
#LOC trae todos los valores, busca la etiqueta Reviews y multiplica -1 a todos los valores extraídos
df_books.loc[:, ['Reviews']] * -1

Reviews
0     -17350
1      -2052
2     -18979
3     -21424
4      -7665
..       ...
545    -9413
546   -14331
547   -14331
548   -14331
549   -14331

[550 rows x 1 columns]

In [104]:
#Busca quienes están cumpliendo la condición dentro de todos los índices.
df_books.loc[:, ['Author']] == 'JJ Smith'

Author
0      True
1     False
2     False
3     False
4     False
..      ...
545   False
546   False
547   False
548   False
549   False

[550 rows x 1 columns]

### Iloc

Filtrar desde index

In [105]:
df_books.iloc[:]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [106]:
#Misma búsqueda que con loc pero ahora es por índice
#A nivel de columna, se le especifica que solo se desea de la 0 a la 3
df_books.iloc[:,0:3]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  
0                    JJ Smith          4.7  
1                Stephen King          4.6  
2          Jordan B. Peterson          4.7  
3               George Orwell          4.7  
4    National Geographic Kids          4.8  
..                        ...          ...  
545               Jeff Kinney          4.9  
546               Jen Sincero          4.7  
547               Jen Sincero          4.7  
548               Jen Sincero          4.7  
549               Jen Sincero          4.7  

[550 rows x 3 columns]

In [107]:
#Operaciones con iloc
df_books.iloc[1,3] * -1

-2052

In [108]:
df_books.iloc[:2, 2:]

User Rating  Reviews  Price  Year        Genre
0          4.7    17350      8  2016  Non Fiction
1          4.6     2052     22  2011      Fiction

## Agregar o eliminar datos con Pandas

### Borrar columnas

In [109]:
#Seleccionar la columna a borrar y el eje
#0 filas y 1 columnas
#IMPORTANTE: Esta salida solo borrará la columna en la salida, más no en el DF
df_books.drop('Genre', axis = 1).head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year  
0  2016  
1  2011

In [110]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

In [111]:
#Se necesita el parámetro inplace para borrarlo correctamente
df_books.drop('Genre', axis = 1, inplace = True)


In [112]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year  
0  2016  
1  2011

In [113]:
#Para usar la sentencia drop sin el inplace se debe asociar al DF.
df_books = df_books.drop('Year', axis = 1)

In [114]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8
1              11/22/63: A Novel  Stephen King          4.6     2052     22

In [115]:
#DEL es una función propia de Python, no aconsejable en el uso de Pandas pero funciona igualmente
del df_books['Price']

### Borrar filas


In [117]:
#Borrar fila 0 del eje 0
df_books.drop(0, axis= 0).head(2)

Name  \
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  
3             George Orwell          4.7    21424  
4  National Geographic Kids          4.8     7665

In [118]:
#Borrar en un rango de 0 a 10 (tuplas)
df_books.drop(range(0,10), axis = 0).head(2)

Name            Author  \
10                          A Man Called Ove: A Novel   Fredrik Backman   
11  A Patriot's History of the United States: From...  Larry Schweikart   

    User Rating  Reviews  
10          4.6    23848  
11          4.6      460

### Agregar columnas

In [122]:
#Traer de nuevo el DF
df_books = pd.read_csv('/content/drive/MyDrive/PandasNumPy/bestsellers-with-categories.csv',
            sep = ',',
            header = 0,
            names = ['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre']
            )

In [123]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

In [124]:
#Agregar nueva columna, definiendola con NumPy en forma no-númerica
df_books['Nueva_columna'] = np.nan

In [125]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  Nueva_columna  
0  2016  Non Fiction            NaN  
1  2011      Fiction            NaN

In [126]:
#Conocer número de filas existentes
df_books.shape[0]

550

In [128]:
#Lista desde 0 a 549 (valor dado con shape)
data = np.arange(0,df_books.shape[0])
data

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [130]:
#Todo rango que se asigne debe tener exactamente la misma cantidad de filas.
df_books['Rango'] = data
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Nueva_columna  Rango  
0              NaN      0  
1              NaN      1  
2              NaN      2  
3              NaN      3  
4              NaN      4  
..             ...    ...  
545            NaN    545  
546            NaN    546  
547            NaN    547  
548            NaN    548  
549            NaN    549  

[550 rows x 9 columns]

### Agregar filas

In [ ]:
#APPEND anexa filas (En este caso se esta anexando a si mismo)
df_books.append(df_books)

## Manejo de datos nulos

In [141]:
#Crear un diccionario con valores nulos
dict = {'Col1': [1, 2, 3, np.nan],
 'Col2': [4, np.nan, 6, 7],
 'Col3': ['a', 'b', 'c', None]
 }

In [132]:
#Usar ese diccionario para crear un DF
df = pd.DataFrame(dict)
df

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

In [134]:
#ISNULL busca valores nulos, dentro del DF
#Si se agrega *1 se convierte en valores de 0 y 1
df.isnull()*1

Col1  Col2  Col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

In [138]:
#Llenar los valores nulos
df.fillna('Missing')

Col1     Col2     Col3
0      1.0      4.0        a
1      2.0  Missing        b
2      3.0      6.0        c
3  Missing      7.0  Missing

In [136]:
#FILLNA se usa para decidir con que llenar los valores nulos
df.fillna(df.mean())

<ipython-input-136-a2478f315f9e>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean())


Col1      Col2  Col3
0   1.0  4.000000     a
1   2.0  5.666667     b
2   3.0  6.000000     c
3   2.0  7.000000  None

In [139]:
#INTERPOLATE crea un valor asumiendo de que trabaja con una serie.
#Es decir, rellena la serie en orden númerico.
#Se usa SIEMPRE Y CUANDO se conozca que los datos estan estructurados.
df.interpolate()

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     c
3   3.0   7.0  None

In [140]:
#DROPNA borra valores nulos
df.dropna()

Col1  Col2 Col3
0   1.0   4.0    a
2   3.0   6.0    c

## Filtrado por condiciones

In [142]:
#Traer de nuevo el DF
df_books = pd.read_csv('/content/drive/MyDrive/PandasNumPy/bestsellers-with-categories.csv',
            sep = ',',
            header = 0,
            names = ['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre']
            )

In [145]:
#La salida va a mostrar quien cumple la condición en lógica booleana (T o F)
mayor2016 = df_books['Year'] > 2016

In [153]:
#Evalua cuales de las condiciones fueron TRUE y los muestra.
#Ambas formas muestran el mismo resultado.
df_books[mayor2016]
df_books[df_books['Year'] > 2016]

Name  \
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
7                       A Gentleman in Moscow: A Novel   
8        A Higher Loyalty: Truth, Lies, and Leadership   
..                                                 ...   
544                                             Wonder   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
7                 Amor Towles          4.7    19699     15  2017      Fiction  
8                 James Comey          4.7     5983      3  2018  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
544             R. J. Palacio          4.8    21625      9  2017      Fiction  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[150 rows x 7 columns]

In [148]:
#Filtrar solo un tipo de registro en una columna.
genreFic = df_books['Genre'] == 'Fiction'

In [150]:
#Cumplir condición en libros de ficción mayores a 2016
df_books[genreFic & mayor2016]

Name             Author  \
3                               1984 (Signet Classics)      George Orwell   
7                       A Gentleman in Moscow: A Novel        Amor Towles   
10                           A Man Called Ove: A Novel    Fredrik Backman   
13                    A Wrinkle in Time (Time Quintet)  Madeleine L'Engle   
40            Brown Bear, Brown Bear, What Do You See?    Bill Martin Jr.   
..                                                 ...                ...   
509                              To Kill a Mockingbird         Harper Lee   
529  What Should Danny Do? (The Power to Choose Ser...          Adir Levy   
534                            Where the Crawdads Sing        Delia Owens   
544                                             Wonder      R. J. Palacio   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)        Jeff Kinney   

     User Rating  Reviews  Price  Year    Genre  
3            4.7    21424      6  2017  Fiction  
7            4.7    19699     15  2017  Fiction  
10           4.6    23848      8  2017  Fiction  
13           4.5     5153      5  2018  Fiction  
40           4.9    14344      5  2017  Fiction  
..           ...      ...    ...   ...      ...  
509          4.8    26234      7  2019  Fiction  
529          4.8     8170     13  2019  Fiction  
534          4.8    87841     15  2019  Fiction  
544          4.8    21625      9  2017  Fiction  
545          4.9     9413      8  2019  Fiction  

[65 rows x 7 columns]

In [152]:
#Negar la condición, en este caso mostrará valores menores o iguales a 2016
df_books[-mayor2016]

Name               Author  \
0                        10-Day Green Smoothie Cleanse             JJ Smith   
1                                    11/22/63: A Novel         Stephen King   
5        A Dance with Dragons (A Song of Ice and Fire)  George R. R. Martin   
6    A Game of Thrones / A Clash of Kings / A Storm...  George R. R. Martin   
9                            A Man Called Ove: A Novel      Fredrik Backman   
..                                                 ...                  ...   
540                                             Wonder        R. J. Palacio   
541                                             Wonder        R. J. Palacio   
542                                             Wonder        R. J. Palacio   
543                                             Wonder        R. J. Palacio   
546  You Are a Badass: How to Stop Doubting Your Gr...          Jen Sincero   

     User Rating  Reviews  Price  Year        Genre  
0            4.7    17350      8  2016  Non Fiction  
1            4.6     2052     22  2011      Fiction  
5            4.4    12643     11  2011      Fiction  
6            4.7    19735     30  2014      Fiction  
9            4.6    23848      8  2016      Fiction  
..           ...      ...    ...   ...          ...  
540          4.8    21625      9  2013      Fiction  
541          4.8    21625      9  2014      Fiction  
542          4.8    21625      9  2015      Fiction  
543          4.8    21625      9  2016      Fiction  
546          4.7    14331      8  2016  Non Fiction  

[400 rows x 7 columns]

## Funciones principales de Pandas

INFO

In [170]:
#Muestra todo sobre el DF
#Mostrar columnas, indices, valores no-nulos, tipo de dato, resume de cuantos tipos de datos hay
#Cuantos registros hay, cuantas columnas hay en total
df_books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Name         550 non-null    object 
 1   Author       550 non-null    object 
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64  
 4   Price        550 non-null    int64  
 5   Year         550 non-null    int64  
 6   Genre        550 non-null    object 
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB


DESCRIBE

In [156]:
#Dará un resumen estadistico de las columnas númericas.
#No.datos, media, desviación estandár, min, media, etc.
df_books.describe()

User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

TAIL

In [157]:
#Devuelve los ultimos registros
df_books.tail(2)

Name       Author  \
548  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
549  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   

     User Rating  Reviews  Price  Year        Genre  
548          4.7    14331      8  2018  Non Fiction  
549          4.7    14331      8  2019  Non Fiction

HEAD

In [158]:
#Devuelve los dos primeros
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

MEMORY_USAGE

In [159]:
#Uso de memoria usada a nivel de DF y por columnas especificas
df_books.memory_usage(deep=True)

Index            128
Name           59737
Author         39078
User Rating     4400
Reviews         4400
Price           4400
Year            4400
Genre          36440
dtype: int64

VALUE_COUNTS

In [160]:
#Contar cuantos valores hay por cada columna dadá.
df_books['Author'].value_counts()

Jeff Kinney                           12
Gary Chapman                          11
Rick Riordan                          11
Suzanne Collins                       11
American Psychological Association    10
                                      ..
Keith Richards                         1
Chris Cleave                           1
Alice Schertle                         1
Celeste Ng                             1
Adam Gasiewski                         1
Name: Author, Length: 248, dtype: int64

In [162]:
df_books.iloc[0]

Name           10-Day Green Smoothie Cleanse
Author                              JJ Smith
User Rating                              4.7
Reviews                                17350
Price                                      8
Year                                    2016
Genre                            Non Fiction
Name: 0, dtype: object

In [163]:
df_books.append(df_books.iloc[0])

<ipython-input-163-16072a3405b2>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_books.append(df_books.iloc[0])


Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
0                        10-Day Green Smoothie Cleanse   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  

[551 rows x 7 columns]

DROP_DUPLICATES

In [168]:
#Elimina duplicados
df_books.drop_duplicates()

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [165]:
#Con Keep borrará el primero y dejará el último que ingreso.
df_books.drop_duplicates(keep= 'last')

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

SORT_VALUES

In [169]:
#Ordenar valores
df_books.sort_values('Year')

Name            Author  \
177                                      I, Alex Cross   James Patterson   
131  Glenn Beck's Common Sense: The Case Against an...        Glenn Beck   
417                                   The Last Lecture      Randy Pausch   
241                       New Moon (The Twilight Saga)   Stephenie Meyer   
72       Diary of a Wimpy Kid: The Last Straw (Book 3)       Jeff Kinney   
..                                                 ...               ...   
150                                               Guts  Raina Telgemeier   
466  The Subtle Art of Not Giving a F*ck: A Counter...       Mark Manson   
462                                 The Silent Patient  Alex Michaelides   
130  Girl, Wash Your Face: Stop Believing the Lies ...     Rachel Hollis   
549  You Are a Badass: How to Stop Doubting Your Gr...       Jen Sincero   

     User Rating  Reviews  Price  Year        Genre  
177          4.6     1320      7  2009      Fiction  
131          4.6     1365     11  2009  Non Fiction  
417          4.7     4028      9  2009  Non Fiction  
241          4.6     5680     10  2009      Fiction  
72           4.8     3837     15  2009      Fiction  
..           ...      ...    ...   ...          ...  
150          4.8     5476      7  2019  Non Fiction  
466          4.6    26490     15  2019  Non Fiction  
462          4.5    27536     14  2019      Fiction  
130          4.6    22288     12  2019  Non Fiction  
549          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
#Ordenar de forma descendiente
df_books.sort_values('Year', asc = False)

## Funciones de agregación (Groupby)

Agrupar objetos que tengan algo en común para su mejor procesamiento.

In [172]:
#Conocer cuantos registros de una columna
#se puede usar con mean(), min(), max()
#El valor que se use para filtrar se convertirá en el índice
df_books.groupby('Author').count()

Name  User Rating  Reviews  Price  Year  Genre
Author                                                                    
Abraham Verghese               2            2        2      2     2      2
Adam Gasiewski                 1            1        1      1     1      1
Adam Mansbach                  1            1        1      1     1      1
Adir Levy                      1            1        1      1     1      1
Admiral William H. McRaven     1            1        1      1     1      1
...                          ...          ...      ...    ...   ...    ...
Walter Isaacson                3            3        3      3     3      3
William Davis                  2            2        2      2     2      2
William P. Young               2            2        2      2     2      2
Wizards RPG Team               3            3        3      3     3      3
Zhi Gang Sha                   2            2        2      2     2      2

[248 rows x 6 columns]

In [173]:
df_books.groupby('Author').sum().loc['William Davis']

<ipython-input-173-4b4655dcf6dc>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_books.groupby('Author').sum().loc['William Davis']


User Rating        8.8
Reviews        14994.0
Price             12.0
Year            4025.0
Name: William Davis, dtype: float64

In [174]:
#Resetear index
df_books.groupby('Author').sum().reset_index()

<ipython-input-174-ecb9159ebf61>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_books.groupby('Author').sum().reset_index()


Author  User Rating  Reviews  Price  Year
0              Abraham Verghese          9.2     9732     22  4021
1                Adam Gasiewski          4.4     3113      6  2017
2                 Adam Mansbach          4.8     9568      9  2011
3                     Adir Levy          4.8     8170     13  2019
4    Admiral William H. McRaven          4.7    10199     11  2017
..                          ...          ...      ...    ...   ...
243             Walter Isaacson         13.7    18668     61  6040
244               William Davis          8.8    14994     12  4025
245            William P. Young          9.2    39440     16  4026
246            Wizards RPG Team         14.4    50970     81  6054
247                Zhi Gang Sha          9.2      257     23  4022

[248 rows x 5 columns]

In [176]:
#Por autor, conocer el nivel de minimo y maximo por cada columna trabajada.
df_books.groupby('Author').agg(['min','max'])

Name  \
                                                                          min   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                             Leonardo da Vinci   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Divine Soul Mind Body Healing and Transmission...   

                                                                               \
                                                                          max   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                                    Steve Jobs   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Soul Healing Miracles: Ancient and New Sacred ...   

                           User Rating      Reviews        Price      Year  \
                                   min  max     min    max   min max   min   
Author                                                                       
Abraham Verghese                   4.6  4.6    4866   4866    11  11  2010   
Adam Gasiewski                     4.4  4.4    3113   3113     6   6  2017   
Adam Mansbach                      4.8  4.8    9568   9568     9   9  2011   
Adir Levy                          4.8  4.8    8170   8170    13  13  2019   
Admiral William H. McRaven         4.7  4.7   10199  10199    11  11  2017   
...                                ...  ...     ...    ...   ...  ..   ...   
Walter Isaacson                    4.5  4.6    3014   7827    20  21  2011   
William Davis                      4.4  4.4    7497   7497     6   6  2012   
William P. Young                   4.6  4.6   19720  19720     8   8  2009   
Wizards RPG Team                   4.8  4.8   16990  16990    27  27  2017   
Zhi Gang Sha                       4.6  4.6      37    220     6  17  2009   

                                        Genre               
                             max          min          max  
Author                                                      
Abraham Verghese            2011      Fiction      Fiction  
Adam Gasiewski              2017  Non Fiction  Non Fiction  
Adam Mansbach               2011      Fiction      Fiction  
Adir Levy                   2019      Fiction      Fiction  
Admiral William H. McRaven  2017  Non Fiction  Non Fiction  
...                          ...          ...          ...  
Walter Isaacson             2017  Non Fiction  Non Fiction  
William Davis               2013  Non Fiction  Non Fiction  
William P. Young            2017      F

In [177]:
#Agrupar por el autor, tomar los reviews con maximo y minimo.
#Sumar los rating
df_books.groupby('Author').agg({'Reviews': ['min', 'max'],
                                'User Rating': 'sum'})

Reviews        User Rating
                               min    max         sum
Author                                               
Abraham Verghese              4866   4866         9.2
Adam Gasiewski                3113   3113         4.4
Adam Mansbach                 9568   9568         4.8
Adir Levy                     8170   8170         4.8
Admiral William H. McRaven   10199  10199         4.7
...                            ...    ...         ...
Walter Isaacson               3014   7827        13.7
William Davis                 7497   7497         8.8
William P. Young             19720  19720         9.2
Wizards RPG Team             16990  16990        14.4
Zhi Gang Sha                    37    220         9.2

[248 rows x 3 columns]

In [179]:
df_books.groupby(['Author', 'Year']).count()

Name  User Rating  Reviews  Price  Genre
Author           Year                                          
Abraham Verghese 2010     1            1        1      1      1
                 2011     1            1        1      1      1
Adam Gasiewski   2017     1            1        1      1      1
Adam Mansbach    2011     1            1        1      1      1
Adir Levy        2019     1            1        1      1      1
...                     ...          ...      ...    ...    ...
Wizards RPG Team 2017     1            1        1      1      1
                 2018     1            1        1      1      1
                 2019     1            1        1      1      1
Zhi Gang Sha     2009     1            1        1      1      1
                 2013     1            1        1      1      1

[493 rows x 5 columns]

## Combinando DataFrames

##Concat



Concatenar dataframes

In [186]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
 'B': ['B0', 'B1', 'B2', 'B3'],
 'C': ['C0', 'C1', 'C2', 'C3'],
 'D': ['D0', 'D1', 'D2', 'D3'],
 })

In [220]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
 'B': ['B4', 'B5', 'B6', 'B7'],
 'C': ['C4', 'C5', 'C6', 'C7'],
 'D': ['D4', 'D5', 'D6', 'D7'],
 })

In [221]:
#Los índices heredan el índice anterior
#IGNORE_INDEX evita que se reescriban los índices originales.
pd.concat([df1, df2], ignore_index= True)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [190]:
#Concatenar de forma horizontal (no es muy usado)
pd.concat([df1, df2], axis= 1)

A   B   C   D   A   B   C   D
0  A0  B0  C0  D0  A4  B4  C4  D4
1  A1  B1  C1  D1  A5  B5  C5  D5
2  A2  B2  C2  D2  A6  B6  C6  D6
3  A3  B3  C3  D3  A7  B7  C7  D7

##Merge

In [225]:
izq = pd.DataFrame({'key': ['k0', 'k1', 'k2', 'k3'],
 'A': ['A0', 'A1', 'A2', 'A3'],
 'B': ['B0', 'B1', 'B2', 'B3'],
 })

In [226]:
der = pd.DataFrame({'key': ['k0', 'k1', 'k2', 'k3'],
  'C': ['C0', 'C1', 'C2', 'C3'],
  'D': ['D0', 'D1', 'D2', 'D3'],
  })

Combinación entre izquierda y derecha

In [227]:
#Siempre el de la izquierda va en la izquierda
#El de la derecha a la derecha en paréntesis
izq.merge(der)

key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2
3  k3  A3  B3  C3  D3

PANDAS esta optimizado para hacer el marge por columnas en común, pero es mejor especificar.

In [206]:
#ON = para especificar.
izq.merge(der, on= 'key')

key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2
3  k3  A3  B3  C3  D3

In [228]:
izq = pd.DataFrame({'key': ['k0', 'k1', 'k2', 'k3'],
 'A': ['A0', 'A1', 'A2', 'A3'],
 'B': ['B0', 'B1', 'B2', 'B3'],
 })
der = pd.DataFrame({'key_2': ['k0', 'k1', 'k2', 'k3'],
 'C': ['C0', 'C1', 'C2', 'C3'],
 'D': ['D0', 'D1', 'D2', 'D3'],
 })

Para poder unir dos DF en donde el valor asignado en ON sea diferente, se debe hacer uso de LEFT_ON y RIGHT_ON


In [213]:
#La estructura es distinta ya que enlista ambos parametros.
izq.merge(der, left_on= 'key', right_on= 'key_2')

key   A   B key_2   C   D
0  k0  A0  B0    k0  C0  D0
1  k1  A1  B1    k1  C1  D1
2  k2  A2  B2    k2  C2  D2

In [229]:
izq = pd.DataFrame({'key': ['k0', 'k1', 'k2', 'k3'],
 'A': ['A0', 'A1', 'A2', 'A3'],
 'B': ['B0', 'B1', 'B2', 'B3'],
 })

#Asignar un valor NaN en el diccionario para trabajarlo.
der = pd.DataFrame({'key_2': ['k0', 'k1', 'k2', np.nan],
 'C': ['C0', 'C1', 'C2', 'C3'],
 'D': ['D0', 'D1', 'D2', 'D3'],
 })

Si se hace merge con un valor NaN, este solo no se mostrará ya que no hay coincidencia.

Al mostrar solo coincidencias se hace un INER JOIN.

In [214]:
#La estructura es distinta ya que enlista ambos parametros.
izq.merge(der, left_on= 'key', right_on= 'key_2')

key   A   B key_2   C   D
0  k0  A0  B0    k0  C0  D0
1  k1  A1  B1    k1  C1  D1
2  k2  A2  B2    k2  C2  D2

Para mostrar el valor nulo existente en la derecha, especificar que se trata de un LEFT

El valor por default es INNER

**HOW = 'LEFT', 'RIGHT' o 'INNER'**

In [217]:
izq.merge(der, left_on= 'key', right_on= 'key_2', how = 'left')

key   A   B key_2    C    D
0  k0  A0  B0    k0   C0   D0
1  k1  A1  B1    k1   C1   D1
2  k2  A2  B2    k2   C2   D2
3  k3  A3  B3   NaN  NaN  NaN

## Join - Index Match

 Es otra herramienta para hacer exactamente lo mismo, una combinación. La diferencia es que join va a ir a los índices y no a columnas específicas.

In [232]:
izq = pd.DataFrame({'A': ['A0','A1','A2'],
  'B':['B0','B1','B2']}, index = ['k0', 'k1', 'k2'])

der = pd.DataFrame({'C': ['C0','C1','C2'],
  'D':['D0','D1','D2']}, index = ['k0', 'k2', 'k3'])


In [234]:
#Unión por index, se puede reutilizar HOW para especificar
izq.join(der, how ='inner')

A   B   C   D
k0  A0  B0  C0  D0
k2  A2  B2  C1  D1

In [ ]:
#Traer TODOS los datos.
izq.join(der, how ='inner')

## Pivot_table

Pivot, básicamente, transforma los valores de determinadas columnas o filas en los índices de un nuevo DataFrame, y la intersección de estos es el valor resultante.

In [235]:
df_books.pivot_table(index='Author',columns='Genre',values='User Rating')

Genre                       Fiction  Non Fiction
Author                                          
Abraham Verghese                4.6          NaN
Adam Gasiewski                  NaN     4.400000
Adam Mansbach                   4.8          NaN
Adir Levy                       4.8          NaN
Admiral William H. McRaven      NaN     4.700000
...                             ...          ...
Walter Isaacson                 NaN     4.566667
William Davis                   NaN     4.400000
William P. Young                4.6          NaN
Wizards RPG Team                4.8          NaN
Zhi Gang Sha                    NaN     4.600000

[248 rows x 2 columns]

Como resultado, los valores de Author pasan a formar el índice por fila y los valores de Genre pasan a formar parte de los índices por columna, y el User Rating se mantiene como valor.

In [239]:
df_books.pivot_table(index='Genre',columns='Year', values='User Rating',aggfunc='sum')

Year          2009   2010   2011   2012   2013   2014   2015   2016   2017  \
Genre                                                                        
Fiction      110.2   92.3   97.0   94.4  109.1  134.3   79.1   89.6  113.7   
Non Fiction  119.0  135.6  130.9  132.2  118.6   96.8  153.3  144.3  119.3   

Year          2018   2019  
Genre                      
Fiction       99.5   96.4  
Non Fiction  133.9  140.6

En este caso tenemos por cada género, la suma a lo largo de los años. Esto es mucho más interesante, ¿verdad? La mejor noticia es que no solo podemos obtener la suma, también podemos obtener la media, la desviación estándar, el conteo, la varianza, etc. Únicamente con cambiar el parámetro aggfunc que traduce función de agrupamiento.

## Melt

El método melt toma las columnas del DataFrame y las pasa a filas, con dos nuevas columnas para especificar la antigua columna y el valor que traía.

In [ ]:
df_books[['Name','Genre']].head(5).melt()

Ahora cada resultado de las dos columnas pasa a una fila de este modo a tipo llave:valor.

In [ ]:
df_books.melt(id_vars='Year',value_vars='Genre')

Simplemente, podemos seleccionar las columnas que no quiero hacer melt usando el parámetro id_vars. Para este caso Year y también la única columna que quiero aplicar el melt, para este caso Genre con la propiedad value_vars.

## Apply

Es un comando muy poderoso que nos deja aplicar funciones a nuestro DataFrame

In [242]:
def two_times(value):
  return value * 2

In [254]:
#Aplicar función
df_books['Reating_2'] = df_books['User Rating'].apply(two_times)
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Reating_2  
0          9.4  
1          9.2  
2          9.4  
3          9.4  
4          9.6  
..         ...  
545        9.8  
546        9.4  
547        9.4  
548        9.4  
549        9.4  

[550 rows x 8 columns]

In [248]:
#APPLY puede trabajar incluso con funciones lambda
df_books['Reating_2'] = df_books['User Rating'].apply(lambda x: x * 3)
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Reating_2  
0         14.1  
1         13.8  
2         14.1  
3         14.1  
4         14.4  
..         ...  
545       14.7  
546       14.1  
547       14.1  
548       14.1  
549       14.1  

[550 rows x 8 columns]

In [253]:
#APPLY directo al DF
#Siempre especificar el eje
df_books['Reating_2'] = df_books.apply(lambda x : x['User Rating'] * 2 if x['Genre'] == 'Fiction' else x['User Rating'], axis= 1)